config/routes.rb
Rails.application.routes.draw do

  root 'customers#index'
  
  resources :customers do
    resources :points, only: [:new, :create] do
    end
  end

  resources :employees do
    member do
      get :passcode_login
    end
  end
    
  get "login" => "sessions#new"
  post "login" => "sessions#create"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :points

  validates_presence_of :first_name, :last_name, :phone, :email, :zip_code
  validates_uniqueness_of :phone, :email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :phone, :zip_code, :numericality => {:only_integer => true}
  validates_length_of :phone, is: 10
  validates_length_of :zip_code, is: 5
end

app/models/employee.rb
class Employee < ActiveRecord::Base

	has_secure_password

  validates_presence_of :user_name, :password, :password_confirmation, :passcode
  validates_uniqueness_of :user_name, :passcode
  validates :passcode, :numericality => {:only_integer => true}
  validates_length_of :passcode, is: 4
  validates_length_of :user_name, :password, minimum: 4
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :customer

  validates_presence_of :point_total, :customer_id, :employee_id
  validates :point_total, :numericality => {:only_integer => true}
  validates_length_of :point_total, minimum: 1, maximum: 3
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :employee_logged_in, only: [:edit, :update, :destroy]

  def new
    # to erase any sessions, from edit back button
    reset_session
    
    if @customer = Customer.find_by(phone: params[:phone])
      flash[:success] = "Welcome back"
      redirect_to @customer
    else
      @customer = Customer.new(phone: params[:phone])
      flash.now[:danger] = "Customer not found, please sign up!"
    end
  end
  
  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:success] = "#{@customer.first_name} #{@customer.last_name} was successfully saved"
      redirect_to @customer
    else
      flash.now[:danger] = "Customer was unsuccessfully saved, please check form"
      render 'new'
    end
  end

  def show
    @customer = Customer.find(params[:id])
    points_array = @customer.points.map(&:point_total)
    @points = points_array.reduce(:+)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update_attributes(customer_params)
      flash[:success] = "Successfully updated"
      redirect_to customer_path(@customer)
    else
      flash.now[:danger] = "Unable to update, please check form"
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :phone, :email, :zip_code, :birthday)
  end

  def employee_logged_in
    @customer = Customer.find(params[:id])
    unless !session[:current_employee_id].nil?
      flash[:danger] = "Employee needs to be logged in to edit"
      redirect_to customer_path(@customer)
    end
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :own_employee, only: [:show, :edit, :update]

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      session[:current_employee_id] = @employee.id
      flash[:success] = "#{@employee.user_name} successfully saved"
      redirect_to @employee
    else
      flash.now[:danger] = "Employee not found"
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(employee_params)
      flash[:success] = "Successfully updated"
      redirect_to @employee
    else
      flash.now[:danger] = "Unable to update, please check the form"
      render :edit
    end
  end

  def passcode_login
    @customer = Customer.find(params[:id])
    @employee = Employee.find_by(passcode: params[:passcode])
    
    if @employee.nil?
      flash[:success] = "Employee not found"
    else
      session[:current_employee_id] = @employee.id
      flash[:success] = "Employee Logged In"
    end

    redirect_to customer_path(@customer)
  end

  private
  def employee_params
    params.require(:employee).permit(:user_name, :password, :password_confirmation, :passcode)
  end

  def own_employee
    @employee = Employee.find(params[:id])
    unless @employee.id == session[:current_employee_id]
      flash[:danger] = "Must log in first"
      redirect_to login_path
    end
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  # before_validation :employee_active on: :create
  # before_action :employee_logged, only: [ :new, :create]


  def new
    @customer = Customer.find(params[:customer_id])
    @point = Point.new

    # Need to fix:
    # to erase admin logged if back button used on create view
    # reset_session
  end

  def create
    @customer = Customer.find(params[:customer_id])
    @point = Point.new(point_params)
    @point.customer_id = @customer.id
    @point.employee_id = session[:current_employee_id]

    if @point.save
      reset_session
      flash[:success] = "Points successfully added"
      redirect_to @customer
    else
      flash.now[:danger] = "Points unsuccessfully added, please check the form"
      render :new
    end
  end

  private
  
  def point_params
    params.require(:point).permit(:point_total)
  end

  # def employee_logged
  #   @employee = Employee.find(params[:id])
  #   unless @employee.id == session[:current_employee_id]
  #     flash[:danger] = "Must log in first"
  #     redirect_to login_path
  #   end
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    employee = Employee.find_by(user_name: params[:session][:user_name])
  	if employee && employee.authenticate(params[:session][:password])
  		flash[:success] = "Welcome Back #{employee.user_name}"
  		redirect_to employee
  	else
  		flash.now[:danger] = "Employee not found"
  		render :new
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def employee_logged_in?
    if !session[:current_employee_id].nil?
    	true
    else
    	false
    end
  end

end

app/helpers/customers_helper.rb
module CustomersHelper

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/customers/_form.html.erb
<div class="form-horizontal">
  <%= form_for @customer do |f| %>
    <%= render "shared/customer_errors" %>
    <div class="form-group">
      <%= f.label :first_name, class: "control-label" %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class: "control-label" %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :phone, class: "control-label" %>
      <%= f.text_field :phone, required: true, pattern: "[0-9]{10}", title: "Number must be 10 digits", maxlength: "10", id: "phone", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "control-label" %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :zip_code, class: "control-label" %>
      <%= f.text_field :zip_code, required: true, pattern: "[0-9]{5}", title: "Zip code must be 5 digits", maxlength: "5", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :birthday, class: "control-label" %>
      <%= f.date_select :birthday, order: [:month, :day, :year], add_month_numbers: true, end_year: Date.today.year - 100, start_year: Date.today.year - 10, class: "form-control" %>
    </div>
    <div class="text-center">
      <%= f.submit "Enter", class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>
</div>

app/views/customers/create.html.erb
<h1>Create a Customer</h1>

<%= render'form' %>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render "form" %>

app/views/customers/index.html.erb
<h1>Enter Your Phone Number:</h1>
<div class="form-inline">
  <%= form_tag(new_customer_path, method: :get) do %>
  <div class="form-group">
    <%= telephone_field_tag :phone, nil, placeholder: "Phone Number", required: true, pattern: "[0-9]{10}", title: "Number must be 10 digits", maxlength: "10", class: "input-lg" %>
  </div>
  <div class="form-group">
    <%= submit_tag "Enter", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>
</div>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

app/views/customers/new.js.erb
$("<%= j(render :new) %>").appendTo("#new-customer");

app/views/customers/show.html.erb
<h1>Hi <%= @customer.first_name %> <%= @customer.last_name %></h1>
<div class="row">
  <% if @points.nil? %>
    <h3>You currently do not have any points.</h3>
  <% else %>
    <h3>Points: <%= @points %></h3>
  <% end %>
</div>
<div class="row">
  <% if employee_logged_in? %>
    <%= link_to "Add Points", new_customer_point_path(@customer), class: "btn btn-primary btn-lg" %>
  <% else %>
    <%= render "employees/passcode_login" %>
  <% end %>
</div>
<div class="row row-space table-responsive">
  <table class="table table-bordered">
    <tr>
      <td>First Name</td>
      <td><%= @customer.first_name %></td>
    </tr>
    <tr>
      <td>Last Name</td>
      <td><%= @customer.last_name %></td>
    </tr>
    <tr>
      <td>Phone</td>
      <td><%= number_to_phone(@customer.phone, area_code: true) %></td>
    </tr>
    <tr>
      <td>Email</td>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <td>Zip-Code</td>
      <td><%= @customer.zip_code %></td>
    </tr>
    <tr>
      <td>Birthday</td>
      <td><%= @customer.birthday.strftime("%B, %d") %></td>
    </tr>
  </table>
</div>
<div class="row">
  <%= link_to "Back", customers_path, class: "btn btn-default" %>
  <% if employee_logged_in? %>
    <%= link_to "Edit profile", edit_customer_path(@customer), class: "btn btn-default" %>
  <% end %>
</div>

app/views/employees/_employee_login.html.erb
<div class="row">
  <div class="form-inline">
    <%= form_tag(login_employee_path, method: :get) do %>
      <div class="form-group">
      <%= password_field_tag :passcode, nil, placeholder: "Staff Passcode", required: true, pattern: "[0-9]{4}", title: "passcode must be 4 digits", maxlength: "4", class: "input-lg" %>
      </div>
      <div class="form-group">
        <%= submit_tag "Enter", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/employees/_form.html.erb
<div class="form-horizontal">
<%= form_for @employee do |f| %>
  <%= render "shared/employee_errors" %>
  <div class="form-group">
    <%= f.text_field :user_name, placeholder: "User Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.password_field :passcode, placeholder: "Passcode", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Enter", class: "btn-primary btn-lg" %>
  </div>
<% end %>
</div>

app/views/employees/_passcode_login.html.erb
<div class="row">
  <div class="form-inline">
    <%= form_tag(passcode_login_employee_path, method: :get) do %>
      <div class="form-group">
      <%= password_field_tag :passcode, nil, placeholder: "Staff Passcode", required: true, pattern: "[0-9]{4}", title: "passcode must be 4 digits", maxlength: "4", class: "input-lg" %>
      </div>
      <div class="form-group">
        <%= submit_tag "Enter", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/employees/edit.html.erb
<h1>Edit Employee Profile</h1>

<%= render "form" %>

app/views/employees/new.html.erb
<h1>Employee Sign Up</h1>

<%= render "form" %>

app/views/employees/show.html.erb
<h1>Employee Profile</h1>

<h3><%= @employee.user_name %></h3>
<h3>Created On: <%= @employee.created_at.strftime("%B %d, %Y at %I:%M:%S%p")  %></h3>

<%= link_to "Edit", edit_employee_path, class: "btn btn-default" %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <p><%= value %></p>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Loyalty App", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Admin", login_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Loyalty</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render "layouts/navbar" %>
  <%= render "layouts/messages" %>

  <div class="container">
    <div id="content" class="jumbotron text-center">
      <%= yield %>
    </div>
  </div>
  
</body>
</html>

app/views/points/new.html.erb
<h1>New Points</h1>
<div class="form-horizontal">
	<%= form_for([@customer, @point]) do |f| %>
		<div class="form-group">
			<%= f.number_field :point_total, placeholder: "Number of points", required: true, pattern: "[0-9]{3}", title: "Number must be a resonable number", maxlength: "3", min: "0" %>
		</div>
		<div class="form-group">
		<%= f.submit "Add Points", data: {confirm: "Proceed adding points?"}, class: "btn btn-primary btn-lg" %>
		</div>
	<% end %>
</div>
<div class="row">
	<%= link_to "Back", customer_path(@customer), class: "btn btn-default" %>
</div>

app/views/shared/_customer_errors.html.erb
<% if @customer.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <div>
        The form contains <%= pluralize(@customer.errors.count, "error") %>:
      </div>
      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_employee_errors.html.erb
<% if @employee.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <div>
        The form contains <%= pluralize(@employee.errors.count, "error") %>:
      </div>
      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>